spring.application.name=mensajeria
twilio.account-sid=AC868f7bea0ffc879d9c4e928587b79ced
twilio.auth-token=2d0527a123bfd2d8511902b77f3aa7dc
twilio.from-number=+19843845365
server.port=8082

jwt.secret=bWljbGF2ZWV4dHJhc2VndXJhZGUzMmNhcmFjdGVyZXNzZGFqa2Zhc2tsamFza2xqYXNrbGpha8OxbGFramFrbGpha2prYWtsamFrc3Nha2pha2Fza2xqZmFzaw==
jwt.expiration=3600000