spring.application.name=mensajeria
twilio.account-sid=AC868f7bea0ffc879d9c4e928587b79ced
twilio.auth-token=c2536fddf23673b5e8c41a890dca82f0
twilio.from-number=+573043405690
server.port=8082

jwt.secret=bWljbGF2ZWV4dHJhc2VndXJhZGUzMmNhcmFjdGVyZXNzZGFqa2Zhc2tsamFza2xqYXNrbGpha8OxbGFramFrbGpha2prYWtsamFrc3Nha2pha2Fza2xqZmFzaw==
jwt.expiration=3600000