spring.application.name=mensajeria
server.port=8082

jwt.secret=bWljbGF2ZWV4dHJhc2VndXJhZGUzMmNhcmFjdGVyZXNzZGFqa2Zhc2tsamFza2xqYXNrbGpha8OxbGFramFrbGpha2prYWtsamFrc3Nha2pha2Fza2xqZmFzaw==
jwt.expiration=3600000